<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OCT-JULIEN" failures="1" tests="19" name="alphaTests.SignUpTest" time="30.258" errors="0" timestamp="2022-07-26T14:19:19 WAT" skipped="0">
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField1" time="2.725"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField2" time="1.223"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField3" time="1.015"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField4" time="1.025"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField5" time="1.043"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField6" time="0.983"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField7" time="0.926"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePhonenumberField1" time="0.955"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePhonenumberField2" time="0.907"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePhonenumberField3" time="0.951"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePasswordField1" time="1.106"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePasswordField2" time="1.155"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePasswordField3" time="1.024"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePasswordField4" time="0.965"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePasswordField5" time="0.947"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateConfirmpasswordField" time="0.999"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateDuplicateUsercreation" time="1.015"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateRequiredFields" time="0.200"/>
  <system-out/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateValidInputsWithValidDataFormat" time="11.094">
    <failure message="expected [https://alphapay.netlify.app/dashboard/overview] but found [https://alphapay.netlify.app/auth/signup]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://alphapay.netlify.app/dashboard/overview] but found [https://alphapay.netlify.app/auth/signup]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at alphaTests.SignUpTest.ValidateValidInputsWithValidDataFormat(SignUpTest.java:176)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateValidInputsWithValidDataFormat -->
  <system-out/>
</testsuite> <!-- alphaTests.SignUpTest -->
